services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: inventaris_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdatanew:/var/lib/postgresql/data
    networks:
      - app-internal  

  backend:
    build: ./backend
    container_name: inventaris_backend
    restart: always
    depends_on:
      - db
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-internal
    volumes:
      - static_data:/app/uploads

  frontend:
    build: ./frontend
    container_name: inventaris_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80 
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL} 
      - CLIENT_MAX_BODY_SIZE=10M
    networks:
      - app-internal 
      - proxy
    volumes:
      - static_data:/usr/share/nginx/html/uploads    

volumes:
  pgdatanew:
  static_data:

networks:
  app-internal: 
  proxy:
    external: true