version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: inventaris_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-internal  

  backend:
    build: ./backend
    container_name: inventaris_backend
    restart: always
    depends_on:
      - db
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-internal 

  frontend:
    build: ./frontend
    container_name: inventaris_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80 
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL} 
    networks:
      - app-internal 
      - proxy        

volumes:
  pgdata:

networks:
  app-internal: 

  proxy:
    external: true